### ISSUE TITLE
Italy doesn't work

### ISSUE THREAD

**Issue by Moppelfett** [MaWoScha/German_LocalePack_it_IT#1]
Hi,
You German, Spanish and French work well but Italy won't work.
I can't see why :(

**Comment by MaWoScha** [comment]
Every Module has the EXACT coding stuff. So it is IMPOSSIBLE, that one module works and the other not. The difference is ONLY another bundle of *.csv files…
One known issue is, that you have to logout and re-login into the admin-side after having installed the module. If not you will experience an 404-error on opening the project/info page.
I will do a little Magento v1.9.3.7 update, but it will be only a google translation...

**Comment by MaWoScha** [comment]
Excuse me, but I didn't remember, that I didn't finished the work on this module. The module itself did not fail but the csv-folder is empty. Without the csv files the module is useless, but the files of
https://github.com/antoniocarboni/magento1_traduzione_italiana
can be used. I added them now. But these file are not actualized since Magento v1.9.2.4.
Next days I will added missing entries up to Magento v1.9.3.7. So the module is almost not complete but working fine.

**Comment by Moppelfett** [comment]
Hi Manfred,
thanks for your reply.

I will try to add the files in the upcoming days.

Best Regards
Ramin

2017-12-08 4:12 GMT+01:00 Manfred Worm Schäfer <notifications@github.com>:

**Comment by MaWoScha** [comment]
OK, I finished to upload all  csv-files and add the missing csv-entries. As I have no idea all is translated by Google Translater. Let me know about translation corrections.

**Comment by MaWoScha** [comment]
I finished the work:
https://github.com/MaWoScha/German_LocalePack_it_IT/releases/tag/v0.7.0
Please give me some feedback after testing ist.
Chiao.

**Comment by MaWoScha** [comment]
Finally added italian localization to
https://github.com/MaWoScha/German_LocaleFallback
https://github.com/MaWoScha/German_LocalePack_en_US

**Comment by MaWoScha** [comment]
One update more:
https://github.com/MaWoScha/German_LocalePack_it_IT/releases/tag/v0.7.1

**Comment by MaWoScha** [comment]
Hello,

please check out the new versions of
https://github.com/MaWoScha/German_LocaleFallback/releases/tag/v0.5.0
and
https://github.com/MaWoScha/German_LocalePack_it_IT/releases/tag/v0.7.1

With kind regards
MaWoScha

2017-12-05 10:10 GMT+01:00 Moppelfett <notifications@github.com>:
